### PR TITLE
3d world building

### PR DESCRIPTION
**Pull request by alicekamada**
Got a barebones rotatable text area working that is editable. Since it's not Ace or CodeMirror, it's gonna need a bit more polish before it's something people will want to use.

### CODE REVIEW

**Comment by alicekamada** [comment]
Rebased to avoid a giant merge conflict / get tests to pass.

**Comment by kf6nux** [comment]
:+1:

**Comment by alicekamada** [comment]
I'm holding this open pending an experiment by @evanhackett, nobody should fold this in until after.

**Comment by alicekamada** [comment]
Experiment was a success, we're going with it.

**Pull request closed without merging**
